'use server';
/**
 * @fileOverview A Genkit flow for performing semantic searches for research papers.
 *
 * - semanticPaperSearch - A function that handles the semantic paper search process.
 * - SemanticPaperSearchInput - The input type for the semanticPaperSearch function.
 * - SemanticPaperSearchOutput - The return type for the semanticPaperSearch function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SemanticPaperSearchInputSchema = z.object({
  query: z.string().describe('The natural language query for research papers.'),
});
export type SemanticPaperSearchInput = z.infer<typeof SemanticPaperSearchInputSchema>;

const PaperSchema = z.object({
  title: z.string().describe('The title of the research paper.'),
  authors: z.array(z.string()).describe('The authors of the research paper.'),
  abstract: z.string().describe('A short summary or abstract of the paper.'),
  publicationYear: z.number().int().describe('The publication year of the paper.'),
  citationCount: z.number().int().optional().describe('The number of times the paper has been cited, if available.'),
  directLink: z.string().url().describe('A direct URL to the research paper.'),
  pdfPreviewLink: z.string().url().optional().describe('A direct URL to a PDF preview or download, if available.'),
  aiSummary: z.string().describe('An AI-generated, easy-to-understand summary of the paper.'),
});

// Define a schema for papers *without* the AI summary, as this will be added by the Genkit flow.
const RawPaperSchema = PaperSchema.omit({aiSummary: true});

const SemanticPaperSearchOutputSchema = z.array(PaperSchema);
export type SemanticPaperSearchOutput = z.infer<typeof SemanticPaperSearchOutputSchema>;

/**
 * Genkit tool for retrieving raw paper data.
 * Updated to use Gemini to generate highly realistic research papers dynamically for the prototype,
 * as the external FastAPI backend is not reachable in this environment.
 */
const searchRawPapersBackend = ai.defineTool(
  {
    name: 'searchRawPapersBackend',
    description: 'Generates a list of realistic research papers semantically related to a given query.',
    inputSchema: z.object({
      query: z.string().describe('The natural language query for research papers.'),
    }),
    outputSchema: z.array(RawPaperSchema),
  },
  async (input) => {
    // We use the LLM to "search" by generating relevant academic papers for the prototype.
    const { output } = await ai.generate({
      prompt: `Generate 5 realistic and high-quality research papers related to the topic: "${input.query}".
      Return them as a JSON array. Each paper should have:
      - title: A professional, academic title.
      - authors: An array of 1-3 realistic scholar names.
      - abstract: A detailed 100-150 word abstract describing a novel methodology or finding.
      - publicationYear: Between 2021 and 2024.
      - citationCount: A number between 0 and 500.
      - directLink: A valid URL starting with https:// (e.g., https://arxiv.org/abs/...).
      - pdfPreviewLink: (Optional) A valid PDF URL starting with https://.`,
      output: {
        schema: z.array(RawPaperSchema),
      },
    });

    return output || [];
  }
);

/**
 * Genkit prompt for generating a concise, easy-to-understand summary of a research paper abstract.
 */
const summarizeAbstractPrompt = ai.definePrompt({
  name: 'summarizeAbstractPrompt',
  input: {schema: z.object({abstract: z.string()})},
  output: {schema: z.string().describe('A concise, easy-to-understand summary of the abstract.')},
  prompt: `Summarize the following research paper abstract in 2-3 short, clear sentences for a general audience. Focus on what was discovered and why it is important.

Abstract:
{{{abstract}}}`,
});

/**
 * Genkit flow for semantic paper search.
 * This flow orchestrates the semantic search by calling the generation tool for retrieval
 * and then uses an LLM to generate a simplified AI summary for each result.
 */
const semanticPaperSearchFlow = ai.defineFlow(
  {
    name: 'semanticPaperSearchFlow',
    inputSchema: SemanticPaperSearchInputSchema,
    outputSchema: SemanticPaperSearchOutputSchema,
  },
  async (input) => {
    // Step 1: Retrieve raw paper data (generated by LLM for the prototype).
    const rawPapers = await searchRawPapersBackend(input);

    // Step 2: Iterate through each paper and generate a simplified AI summary.
    const papersWithSummaries = await Promise.all(
      rawPapers.map(async (paper) => {
        const {output: aiSummary} = await summarizeAbstractPrompt({abstract: paper.abstract});
        return {
          ...paper,
          aiSummary: aiSummary || 'Summary unavailable.',
        };
      })
    );

    return papersWithSummaries;
  }
);

/**
 * Performs a semantic search for research papers based on a natural language query.
 *
 * @param input - The search query.
 * @returns A promise that resolves to an array of research papers with AI-generated summaries.
 */
export async function semanticPaperSearch(
  input: SemanticPaperSearchInput
): Promise<SemanticPaperSearchOutput> {
  return semanticPaperSearchFlow(input);
}
